name: process_cards
description: Offline project steps app with docx export.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI + state
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  
  pdf: ^3.11.3

  # Local DB
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4

  # Files + ids
  uuid: ^4.5.1
  intl: ^0.20.2

  # Images
  image_picker: ^1.1.2

  # Export/share
  share_plus: ^12.0.1

  docx_creator: ^1.0.6
  
  photo_manager: ^3.6.0
  
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    
flutter_launcher_icons:
  ios: true
  android: true
  image_path: assets/steps.png
  remove_alpha_ios: true


